---
# file: oracle-java/tasks/check_environment.yml
#
# task to set host facts:
#   - Java is installed?
#   - which Java version is installed?
#

- name: determine if Java is already installed
  shell: which java
  register: oracle_java_task_installed
  ignore_errors: yes
  changed_when: False
# oracle_java_installed.rc == 0 : installed
# oracle_java_installed.rc == 1 : not installed


- name: set fact oracle_java_installed
  set_fact:
    oracle_java_installed={{ oracle_java_task_installed.rc == 0 }}
  when: oracle_java_task_installed is defined and oracle_java_task_installed.rc is defined
  changed_when: False

- name: determine which Java version is installed
  shell: java -version 2>&1 | head -n 1 | awk '{ print $3 }' | awk -F '"' '{ print $2 }'
  when: oracle_java_installed is defined
  register: oracle_java_task_version
  changed_when: False

- name: set fact oracle_java_installed_version
  set_fact:
    oracle_java_version_installed={{ oracle_java_task_version.stdout }}
  when: oracle_java_task_version is defined and oracle_java_task_version.stdout is defined
  changed_when: False

- debug:
    var="{{ item }}"
  when: "{{ item }} is defined and debug | default(false)"
  with_items:
    - oracle_java_installed
    - oracle_java_task_installed
    - oracle_java_task_version
    - oracle_java_version_installed
    - oracle_java_version_string
