---
# file: oracle-java/tasks/redhat/main.yml
#
# Task file to install Oracle Java Development Kit in a system with a Redhat based Linux distribution.
#

- name: download Java RPM
  shell:
    "curl -L  -H 'Cookie:oraclelicense=accept-securebackup-cookie' -o {{ oracle_java_dir_source }}/{{ oracle_java_rpm_filename }} {{ oracle_java_rpm_url }}"
  args:
    creates: "{{ oracle_java_dir_source }}/{{ oracle_java_rpm_filename }}"
  register: oracle_java_task_rpm_download
  become: yes
  tags:
    - installation

- name: install RPM
  action: "{{ ansible_pkg_mgr }} name={{ oracle_java_dir_source }}/{{ oracle_java_rpm_filename }} state=present"
  when: not oracle_java_task_rpm_download|skipped
  become: yes
  tags:
    - installation

- name: set Java version as default
  alternatives:
    name="{{ item.exe }}"
    link="/usr/bin/{{ item.exe }}"
    path="{{ item.path }}/{{ item.exe }}"
  with_items:
    - { path: "{{ oracle_java_home }}/jre/bin", exe: 'java' }
    - { path: "{{ oracle_java_home }}/jre/bin", exe: 'keytool' }
    - { path: "{{ oracle_java_home }}/bin", exe: 'javac' }
    - { path: "{{ oracle_java_home }}/bin", exe: 'javadoc' }
  become: yes
  when: (
          oracle_java_set_as_default and
          oracle_java_task_rpm_download is defined and
          oracle_java_task_rpm_download|changed
        ) or (
          oracle_java_set_as_default and
          oracle_java_installed is defined and
          oracle_java_installed and
          oracle_java_version_installed is defined and
          oracle_java_version_installed != oracle_java_version_string)
  register: oracle_java_task_set_default

- name: in case there were changes, check host environment again
  include: ../check_environment.yml
  when: (
          oracle_java_task_rpm_download is defined and
          not oracle_java_task_rpm_download|skipped
        ) or (
          oracle_java_task_set_default is defined and
          oracle_java_task_set_default|changed
        )
